"""
Dimer Equivalence Classifier for Atoms in Crystals
====================================================
Identifies geometrically distinct dimer types containing a reference atom A
using the Euclidean normalizer N_E(G) framework.

Framework summary:
- Candidate partners are generated by applying all space group operations to A
- Equivalence classes are determined by the stabilizer S_x^{N_E(G)}
- Two partners are equivalent if any element of S_x^{N_E(G)} maps one to the other
- Unrooted merging is automatic for atoms (distance-only identity)

Currently implemented space groups: P1, P-1, P4
Extend by adding entries to SPACE_GROUPS and NORMALIZER_EXTRA_GENERATORS.
"""

import numpy as np
from itertools import product as iterproduct


# ------------------------------------------------------------------------------
# Tolerance for floating point comparisons
# ------------------------------------------------------------------------------
TOL = 1e-6


# ------------------------------------------------------------------------------
# Space group definitions
# Each entry: list of (rotation matrix, translation vector) in fractional coords
# Rotations are 3x3 integer matrices, translations are length-3 float vectors
# ------------------------------------------------------------------------------


def _r(matrix_rows):
    return np.array(matrix_rows, dtype=float)


def _t(vec):
    return np.array(vec, dtype=float)


SPACE_GROUPS = {
    # P1 - only identity
    1: [
        (_r([[1, 0, 0], [0, 1, 0], [0, 0, 1]]), _t([0, 0, 0])),
    ],
    # P-1 - identity + inversion
    2: [
        (_r([[1, 0, 0], [0, 1, 0], [0, 0, 1]]), _t([0, 0, 0])),
        (_r([[-1, 0, 0], [0, -1, 0], [0, 0, -1]]), _t([0, 0, 0])),
    ],
    # P4 - fourfold rotation along c
    75: [
        (_r([[1, 0, 0], [0, 1, 0], [0, 0, 1]]), _t([0, 0, 0])),  # E
        (_r([[0, -1, 0], [1, 0, 0], [0, 0, 1]]), _t([0, 0, 0])),  # 4+
        (_r([[-1, 0, 0], [0, -1, 0], [0, 0, 1]]), _t([0, 0, 0])),  # 2
        (_r([[0, 1, 0], [-1, 0, 0], [0, 0, 1]]), _t([0, 0, 0])),  # 4-
    ],
}


# ------------------------------------------------------------------------------
# Euclidean normalizer additional generators
# Each entry: list of (rotation, translation) BEYOND the space group generators
# These are the extra coset representatives from ITA Table 3.5.2
# ------------------------------------------------------------------------------

NORMALIZER_EXTRA_GENERATORS = {
    # P1: N_E = R3 x O(3) - all translations and rotations
    # In practice for finite enumeration we use the space group itself
    1: [],
    # P-1: N_E adds all translations t = (1/2)(a+b+c) combinations
    # and the identity (inversion already in G)
    # The additional generator is a (1/2,1/2,1/2) translation
    2: [
        (_r([[1, 0, 0], [0, 1, 0], [0, 0, 1]]), _t([0.5, 0.5, 0.5])),
    ],
    # P4: N_E(P4) = P4/mmm
    # Additional generators beyond P4:
    #   - translation (1/2, 1/2, 0)
    #   - inversion through origin
    #   - mirror m110: (y, x, z)
    #   - translation (0, 0, t) is continuous - ignored for finite enumeration
    75: [
        (_r([[1, 0, 0], [0, 1, 0], [0, 0, 1]]), _t([0.5, 0.5, 0.0])),  # t(1/2,1/2,0)
        (_r([[-1, 0, 0], [0, -1, 0], [0, 0, -1]]), _t([0, 0, 0])),  # inversion
        (_r([[0, 1, 0], [1, 0, 0], [0, 0, 1]]), _t([0, 0, 0])),  # m110: (y,x,z)
    ],
}


# ------------------------------------------------------------------------------
# Lattice utilities
# ------------------------------------------------------------------------------


def lattice_matrix(a, b, c, alpha, beta, gamma):
    """
    Build Cartesian lattice matrix from unit cell parameters.
    Columns are lattice vectors a, b, c.
    Angles in degrees.
    """
    alpha, beta, gamma = np.radians([alpha, beta, gamma])
    ax = a
    bx = b * np.cos(gamma)
    by = b * np.sin(gamma)
    cx = c * np.cos(beta)
    cy = c * (np.cos(alpha) - np.cos(beta) * np.cos(gamma)) / np.sin(gamma)
    cz = np.sqrt(max(c**2 - cx**2 - cy**2, 0))
    return np.array([[ax, bx, cx], [0, by, cy], [0, 0, cz]])


def frac_to_cart(frac, lat):
    """Convert fractional to Cartesian coordinates."""
    return lat @ frac


def cart_to_frac(cart, lat):
    """Convert Cartesian to fractional coordinates."""
    return np.linalg.inv(lat) @ cart


def wrap(frac):
    """Wrap fractional coordinates to [0, 1)."""
    return frac % 1.0


def frac_dist(f1, f2, lat):
    """Cartesian distance between two fractional coordinate points."""
    diff = frac_to_cart(f1, lat) - frac_to_cart(f2, lat)
    return np.linalg.norm(diff)


def close_frac(f1, f2, tol=TOL):
    """Check if two fractional coords are equal modulo lattice translations."""
    diff = f1 - f2
    diff_wrapped = diff - np.round(diff)
    return np.allclose(diff_wrapped, 0, atol=tol)


# ------------------------------------------------------------------------------
# Group generation
# ------------------------------------------------------------------------------


def compose(op1, op2):
    """Compose two symmetry operations (R1, t1) and (R2, t2): apply op2 then op1."""
    R1, t1 = op1
    R2, t2 = op2
    return (R1 @ R2, R1 @ t2 + t1)


def inverse_op(op):
    """Compute inverse of a symmetry operation."""
    R, t = op
    Rinv = np.linalg.inv(R)
    return (Rinv, -Rinv @ t)


def apply_op(op, x):
    """Apply symmetry operation to fractional coordinate x."""
    R, t = op
    return R @ x + t


def ops_equal(op1, op2, tol=TOL):
    """Check if two symmetry operations are equal modulo lattice translations."""
    R1, t1 = op1
    R2, t2 = op2
    if not np.allclose(R1, R2, atol=tol):
        return False
    dt = t1 - t2
    dt_wrapped = dt - np.round(dt)
    return np.allclose(dt_wrapped, 0, atol=tol)


def generate_group(generators, max_order=1000):
    """
    Generate all elements of a group from a list of generator operations.
    Each operation is (R, t) where R is 3x3 rotation and t is translation.
    Translations are kept modulo 1 (fractional coords).
    """

    # Normalize translations to [0,1)
    def normalize(op):
        R, t = op
        return (R, t % 1.0)

    identity = (_r([[1, 0, 0], [0, 1, 0], [0, 0, 1]]), _t([0, 0, 0]))
    elements = [normalize(identity)]

    def already_in(op, elems):
        for e in elems:
            if ops_equal(op, e):
                return True
        return False

    # Add generators
    for g in generators:
        ng = normalize(g)
        if not already_in(ng, elements):
            elements.append(ng)

    # Close under composition
    changed = True
    iterations = 0
    while changed and iterations < max_order:
        changed = False
        iterations += 1
        new_elements = []
        for e1 in elements:
            for e2 in elements:
                prod = normalize(compose(e1, e2))
                if not already_in(prod, elements) and not already_in(
                    prod, new_elements
                ):
                    new_elements.append(prod)
                    changed = True
        elements.extend(new_elements)

    return elements


# ------------------------------------------------------------------------------
# Stabilizer computation
# ------------------------------------------------------------------------------


def compute_stabilizer(x, group_elements, tol=TOL):
    """
    Compute the stabilizer of point x in a group.
    Returns all group elements that fix x modulo lattice translations.
    """
    stabilizer = []
    for op in group_elements:
        gx = apply_op(op, x)
        if close_frac(gx, x, tol):
            stabilizer.append(op)
    return stabilizer


# ------------------------------------------------------------------------------
# Candidate partner generation
# ------------------------------------------------------------------------------


def generate_candidates(x, sg_elements, lat, r_cut, n_shells=2):
    """
    Generate all candidate dimer partners within r_cut of x.
    Applies each space group operation and considers neighboring unit cells.

    Returns list of (fractional_position, operation, cell_offset) tuples.
    """
    candidates = []
    offsets = list(iterproduct(range(-n_shells, n_shells + 1), repeat=3))

    for op in sg_elements:
        gx_frac = apply_op(op, x)

        for offset in offsets:
            n = np.array(offset, dtype=float)
            partner_frac = gx_frac + n

            # Skip if this is the reference atom itself
            if close_frac(partner_frac, x):
                continue

            # Check distance
            d = frac_dist(partner_frac, x, lat)
            if d < r_cut:
                # Check not already in list
                already = False
                for c in candidates:
                    if close_frac(c[0], partner_frac):
                        already = True
                        break
                if not already:
                    candidates.append((partner_frac, op, offset))

    return candidates


# ------------------------------------------------------------------------------
# Equivalence classification
# ------------------------------------------------------------------------------


def classify_dimers(x, candidates, stabilizer, lat, tol=TOL):
    """
    Partition candidates into equivalence classes under the stabilizer.
    Two candidates are equivalent if any stabilizer element maps one to the other.

    Returns list of equivalence classes, each a list of candidate indices.
    """
    n = len(candidates)
    # Union-find
    parent = list(range(n))

    def find(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    def union(i, j):
        pi, pj = find(i), find(j)
        if pi != pj:
            parent[pi] = pj

    # For each pair of candidates, check if stabilizer relates them
    for i in range(n):
        for j in range(i + 1, n):
            pi_frac = candidates[i][0]
            pj_frac = candidates[j][0]
            for h in stabilizer:
                h_pi = apply_op(h, pi_frac)
                if close_frac(h_pi, pj_frac, tol):
                    union(i, j)
                    break

    # Collect classes
    classes = {}
    for i in range(n):
        root = find(i)
        if root not in classes:
            classes[root] = []
        classes[root].append(i)

    return list(classes.values())


# ------------------------------------------------------------------------------
# Main interface
# ------------------------------------------------------------------------------


def find_distinct_dimers(
    sg_number, x_frac, lat_params, r_cut, n_shells=2, verbose=True
):
    """
    Find all distinct dimer types for an atom at x_frac in a crystal.

    Parameters
    ----------
    sg_number : int
        Space group number (must be in SPACE_GROUPS)
    x_frac : array-like
        Fractional coordinates of reference atom, shape (3,)
    lat_params : tuple
        (a, b, c, alpha, beta, gamma) unit cell parameters
    r_cut : float
        Cutoff distance in Angstroms
    n_shells : int
        Number of neighboring unit cells to search in each direction
    verbose : bool
        Print detailed output

    Returns
    -------
    classes : list of lists
        Each inner list contains (partner_frac, distance) tuples for one dimer class
    """
    x = np.array(x_frac, dtype=float)
    a, b, c, alpha, beta, gamma = lat_params
    lat = lattice_matrix(a, b, c, alpha, beta, gamma)

    if verbose:
        print(f"Space group: {sg_number}")
        print(f"Reference atom: {x}")
        print(f"Lattice: a={a}, b={b}, c={c}, α={alpha}, β={beta}, γ={gamma}")
        print(f"Cutoff: {r_cut} Å, shells: {n_shells}")
        print()

    # --- Step 1: Build space group elements ---
    if sg_number not in SPACE_GROUPS:
        raise ValueError(
            f"Space group {sg_number} not implemented. "
            f"Available: {list(SPACE_GROUPS.keys())}"
        )

    sg_generators = SPACE_GROUPS[sg_number]
    sg_elements = generate_group(sg_generators)

    if verbose:
        print(f"Space group order (in unit cell): {len(sg_elements)}")

    # --- Step 2: Build N_E(G) elements ---
    extra_generators = NORMALIZER_EXTRA_GENERATORS.get(sg_number, [])
    all_generators = sg_generators + extra_generators
    ne_elements = generate_group(all_generators)

    if verbose:
        print(f"Normalizer order (in unit cell): {len(ne_elements)}")

    # --- Step 3: Compute stabilizer S_x^{N_E(G)} ---
    stabilizer = compute_stabilizer(x, ne_elements)

    if verbose:
        print(f"Stabilizer order: {len(stabilizer)}")
        print("Stabilizer elements:")
        for op in stabilizer:
            R, t = op
            print(f"  R={R.astype(int).tolist()}, t={np.round(t, 4).tolist()}")
        print()

    # --- Step 4: Generate candidate partners ---
    candidates = generate_candidates(x, sg_elements, lat, r_cut, n_shells)

    if verbose:
        print(f"Candidate partners within {r_cut} Å: {len(candidates)}")
        for i, (pf, op, cell) in enumerate(candidates):
            d = frac_dist(pf, x, lat)
            print(f"  [{i}] frac={np.round(pf, 4)}, cell={cell}, dist={d:.4f} Å")
        print()

    # --- Step 5: Classify under stabilizer ---
    if len(candidates) == 0:
        if verbose:
            print("No candidates found. Try increasing r_cut or n_shells.")
        return []

    eq_classes = classify_dimers(x, candidates, stabilizer, lat)

    # --- Step 6: Format output ---
    result = []
    for cls in eq_classes:
        members = []
        for idx in cls:
            pf, op, cell = candidates[idx]
            d = frac_dist(pf, x, lat)
            members.append((pf, d))
        result.append(members)

    # Sort classes by minimum distance
    result.sort(key=lambda cls: min(d for _, d in cls))

    if verbose:
        print(f"Distinct dimer types: {len(result)}")
        print()
        for i, cls in enumerate(result):
            print(f"Dimer type {i + 1} ({len(cls)} equivalent instances):")
            for pf, d in cls:
                print(f"  partner at {np.round(pf, 4)}, distance={d:.4f} Å")
        print()

    return result


# ------------------------------------------------------------------------------
# Example usage
# ------------------------------------------------------------------------------

if __name__ == "__main__":
    print("=" * 60)
    print("Example 1: P4, atom at (1/4, 1/4, 0), a=b=4, c=6 Å")
    print("=" * 60)
    find_distinct_dimers(
        sg_number=75,
        x_frac=[0.25, 0.25, 0.0],
        lat_params=(4.0, 4.0, 6.0, 90, 90, 90),
        r_cut=5.0,
        n_shells=1,
    )

    print("=" * 60)
    print("Example 2: P4, atom at general position (0.1, 0.4, 0)")
    print("=" * 60)
    find_distinct_dimers(
        sg_number=75,
        x_frac=[0.1, 0.4, 0.0],
        lat_params=(4.0, 4.0, 6.0, 90, 90, 90),
        r_cut=5.0,
        n_shells=1,
    )

    print("=" * 60)
    print("Example 3: P-1, atom at general position (0.1, 0.2, 0.3)")
    print("=" * 60)
    find_distinct_dimers(
        sg_number=2,
        x_frac=[0.1, 0.2, 0.3],
        lat_params=(5.0, 6.0, 7.0, 80, 85, 95),
        r_cut=6.0,
        n_shells=1,
    )

    print("=" * 60)
    print("Example 4: P1, atom at (0.3, 0.3, 0.3)")
    print("=" * 60)
    find_distinct_dimers(
        sg_number=1,
        x_frac=[0.3, 0.3, 0.3],
        lat_params=(5.0, 5.0, 5.0, 90, 90, 90),
        r_cut=6.0,
        n_shells=1,
    )
